ekf_slam:
  ros__parameters:
    wheel_base: 0.33
    control_noise:
      x: 0.01
      y: 0.01
      theta: 0.01
    measurement_noise:
      range: 0.05
      bearing: 0.05
    data_association:
      threshold: 5.991
