ekf_slam:
  ros__parameters:
    control_noise:
      x: 0.01
      y: 0.01
      theta: 0.01
    measurement_noise:
      range: 0.05
      bearing: 0.05
    data_association:
      threshold: 5.991
      ratio: 0.8
    scan_downsample:
      step: 10
    map:
      width: 1500
      height: 1500
      resolution: 0.05
    wheel_base: 0.33
